apiVersion: v1
kind: Pod
metadata:
  name: aws-k8s-demo
  namespace: default
spec:
  serviceAccountName: aws-k8s-oidc
  containers:
    - name: aws-cli
      image: amazon/aws-cli
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
  tolerations:
    - operator: Exists
      effect: NoSchedule
